language: bash
sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

notifications:
  email:
    recipients:
      - kees.van.voorthuizen@gmail.com
    on_success: never
    on_failure: always

before_script:
  - chmod +x *.sh
  - ./install.sh

script:
  - ./shebang.sh
  - ./shebang.sh update
  - ./shebang.sh install keesvv/shebang master
  - ./shebang.sh remove sample-package

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage shebang.sh &&
  bash <(curl -s https://codecov.io/bash)
